name: xllm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.18
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - transformers
      - openai
      - pandas
      - einops
      - accelerate
      - sentencepiece
      - protobuf
      - transformers_stream_generator
      - tiktoken
      - autoawq
      - importlib-metadata
      - auto-gptq
      - sympy
      - llm
      - fastchat
      - numpy
      - vllm
      - anthropic
      - google.generativeai
      - tqdm
