#!/bin/bash
# 从GPFS快照恢复Step 26 checkpoint的指南

echo "📋 GPFS快照恢复指南"
echo "==================="
echo ""
echo "根据mmlssnapshot的输出，系统有以下快照可用:"
echo ""
echo "快照列表 (hpc fileset):"
mmlssnapshot gpfs 2>/dev/null | grep "hpc" | head -5
echo ""
echo "Step 26 checkpoint应该在以下时间之前被删除:"
echo "  - Step 28创建时间: 2026-01-10 17:12"
echo "  - Step 29创建时间: 2026-01-10 19:29"
echo ""
echo "因此，1月8日或更早的快照可能包含Step 26。"
echo ""
echo "访问快照的方法:"
echo "1. 通过GPFS快照路径 (需要确认实际路径):"
echo "   ls /gpfs/.snapshots/@GMT-2026.01.08-07.00.31/hpc/p32013/neurons/RA-GRPO/checkpoints/easy_r1/qwen3_4b_think_safety_2/"
echo ""
echo "2. 或者联系系统管理员获取快照访问权限"
echo ""
echo "3. 如果找到，恢复命令:"
echo "   cp -r /gpfs/.snapshots/@GMT-YYYY.MM.DD-HH.MM.SS/hpc/p32013/neurons/RA-GRPO/checkpoints/easy_r1/qwen3_4b_think_safety_2/global_step_26 \\"
echo "         ./checkpoints/easy_r1/qwen3_4b_think_safety_2/"
echo ""
echo "4. 或者尝试VSCode的本地历史功能:"
echo "   - 在VSCode中右键点击checkpoints目录"
echo "   - 选择 'Local History' 或 'Timeline'"
echo "   - 查找Step 26的版本"
echo ""
